docs: add caching in other workflows

diff --git a/.github/workflows/nightly-docker-build.yaml b/.github/workflows/nightly-docker-build.yaml
--- a/.github/workflows/nightly-docker-build.yaml
+++ b/.github/workflows/nightly-docker-build.yaml
@@ -30,11 +30,19 @@ jobs:
 
       - run: npm ci
 
-      - name: Compile
+      - name: Build
         run: |
-          touch .env
-          make build
-
+          set +e  # Disable automatic stop on command failure
+          npm run build
+          exit_code=$?
+          echo "Build command exit code: $exit_code"
+          echo "BUILD_EXIT_CODE=$exit_code">> $GITHUB_ENV
+      
+      - name: Build with cached packs
+        if: ${{ env.BUILD_EXIT_CODE == '5' }}
+        uses: ./.github/actions/build-cached-packs
+        with:
+          gh-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
diff --git a/.github/workflows/release-branch-pr.yaml b/.github/workflows/release-branch-pr.yaml
--- a/.github/workflows/release-branch-pr.yaml
+++ b/.github/workflows/release-branch-pr.yaml
@@ -61,4 +61,16 @@ jobs:
             🤖 Netlify configured to enable preview build for branch:  ${{env.GITHUB_BRANCH}} . Subsequent commits will automatically trigger a Netlify build preview.
         refresh-message-position: false
 
-    - run: npm run build
+    - name: Build
+      run: |
+        set +e  # Disable automatic stop on command failure
+        npm run build
+        exit_code=$?
+        echo "Build command exit code: $exit_code"
+        echo "BUILD_EXIT_CODE=$exit_code">> $GITHUB_ENV
+      
+    - name: Build with cached packs
+      if: ${{ env.BUILD_EXIT_CODE == '5' }}
+      uses: ./.github/actions/build-cached-packs
+      with:
+        gh-token: ${{ secrets.GITHUB_TOKEN }}
diff --git a/.github/workflows/release-preview.yaml b/.github/workflows/release-preview.yaml
--- a/.github/workflows/release-preview.yaml
+++ b/.github/workflows/release-preview.yaml
@@ -48,17 +48,24 @@ jobs:
           echo "User-agent: *" >> static/robots.txt
           echo "Disallow: /" >> static/robots.txt
           echo "Sitemap: https://docs-latest.spectrocloud.com/sitemap.xml" >> static/robots.txt
-        
 
       - name: Ensure noIndex is set
         id: check_noindex
         run: node scripts/noindex_docusaurus_config.js $PWD
-          
-
+      
       - name: Build
         run: |
-          touch .env
-          make build
+          set +e  # Disable automatic stop on command failure
+          npm run build
+          exit_code=$?
+          echo "Build command exit code: $exit_code"
+          echo "BUILD_EXIT_CODE=$exit_code">> $GITHUB_ENV
+      
+      - name: Build with cached packs
+        if: ${{ env.BUILD_EXIT_CODE == '5' }}
+        uses: ./.github/actions/build-cached-packs
+        with:
+          gh-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Deploy Preview
         run: |
diff --git a/.github/workflows/screenshot_capture.yaml b/.github/workflows/screenshot_capture.yaml
--- a/.github/workflows/screenshot_capture.yaml
+++ b/.github/workflows/screenshot_capture.yaml
@@ -44,8 +44,19 @@ jobs:
       - name: Install Playwright browsers
         run: npx playwright install --with-deps chromium
 
-      - name: Build Website
-        run: make build
+      - name: Build
+        run: |
+          set +e  # Disable automatic stop on command failure
+          npm run build
+          exit_code=$?
+          echo "Build command exit code: $exit_code"
+          echo "BUILD_EXIT_CODE=$exit_code">> $GITHUB_ENV
+      
+      - name: Build with cached packs
+        if: ${{ env.BUILD_EXIT_CODE == '5' }}
+        uses: ./.github/actions/build-cached-packs
+        with:
+          gh-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Upload Build
         uses: actions/upload-artifact@v4
