docs: add intermediary step

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -107,6 +107,14 @@ jobs:
             exit 1
           fi
       
+      - name: Check Build Exit Code
+        run: |
+          # Exit codes are not immediately propagated. We use an intermediary step.
+          if [ "$BUILD_EXIT_CODE" != "0" ]; then
+            echo "Build failed with exit code $BUILD_EXIT_CODE."
+            exit 1
+          fi
+      
       - name: Build with cached packs
         if: env.BUILD_EXIT_CODE == '5' 
         uses: ./.github/actions/build-cached-packs
