chore: fixed logic

diff --git a/.github/workflows/visual-comparison.yaml b/.github/workflows/visual-comparison.yaml
--- a/.github/workflows/visual-comparison.yaml
+++ b/.github/workflows/visual-comparison.yaml
@@ -55,26 +55,72 @@ jobs:
       - name: Take screenshots with Playwright
         run: make test-visual-ci
 
-      - name: Push HTML Report
-        timeout-minutes: 3
-        run: |
-          git add .
-          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
-          while true; do
-            git pull --rebase
-            if [ $? -ne 0 ]; then
-              echo "Failed to rebase. Please review manually."
-              exit 1
-            fi
+      # - name: Upload screenshots
+      #   uses: actions/upload-artifact@v4
+      #   id: screenshots
+      #   with:
+      #     name: "snapshots"
+      #     path: |
+      #       screenshots/
+      #     if-no-files-found: error
+      #     retention-days: 1
 
-            git push
-            if [ $? -eq 0 ]; then
-              echo "Successfully pushed HTML report to repo."
-              exit 0
-            fi
-          done
+      - name: Upload Report
+        uses: actions/upload-artifact@v4
+        id: report
+        with:
+          name: "report"
+          path: |
+            playwright-report/
+          if-no-files-found: error
+          retention-days: 1  
 
-          
-      - name: GH Pages URL
-        run: |
-          echo "::notice title=📋 Published Playwright Test Report::https://spectrocloud.github.io/librarium/$HTML_REPORT_URL_PATH"
+
+  publish_report:
+    name: Publish HTML Report
+    if: "success()"
+    needs: [test]
+    runs-on: ubuntu-latest
+    continue-on-error: true    
+    steps: 
+
+    - name: Checkout GitHub Pages Branch
+      uses: actions/checkout@v4
+      with:
+        ref: gh-pages  
+
+    - name: Set Git User
+          # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+      run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+    - name: Download zipped HTML report
+      uses: actions/download-artifact@v4
+      with:
+        name: report
+        path: ${{ env.HTML_REPORT_URL_PATH }}
+
+    - name: Push HTML Report
+      timeout-minutes: 3
+      run: |
+        git add .
+        git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+        while true; do
+          git pull --rebase
+          if [ $? -ne 0 ]; then
+            echo "Failed to rebase. Please review manually."
+            exit 1
+          fi
+
+          git push
+          if [ $? -eq 0 ]; then
+            echo "Successfully pushed HTML report to repo."
+            exit 0
+          fi
+        done
+
+        
+    - name: GH Pages URL
+      run: |
+        echo "::notice title=📋 Published Playwright Test Report::https://spectrocloud.github.io/librarium/$HTML_REPORT_URL_PATH"
